$ANSIBLE_VAULT;1.1;AES256
34626339666234626366393563646161366339623737383232333830636662336137323132633835
3664376237343431396338616635613535323161363136360a373532316133636231396234313464
63356366336331383532613530316461323138326361396361653161356131656131373462303062
3537653361643438380a343162336139646361343837613635353837616666396531353362366430
39386163653235336434313163663438643765343032316335356539666138666633353436643864
63613630303632366562383762356237383561343830343165663534366535313362313664323634
366237646235303732656234623232353832
